name: pho_features
channels:
  - pykaldi
  - conda-forge
  - coml
dependencies:
  - numpy
  - sox
  - pandas
  - scipy
  - pykaldi-cpu
  - shennong
  - pip
  - pip:
    - tqdm
    - praat-parselmouth
    - pysndfx
    - pysptk
    - numba
    - jupyter
