name: pho_features
channels:
  - pykaldi
  - conda-forge
  - coml
dependencies:
  - pykaldi-cpu
  - shennong
  - pip
  - pip:
    - tqdm
    - praat-parselmouth
    - pysndfx
    - pysptk
    - numba
    - jupyter
    - scipy
    - numpy
    - pandas
    - sox
    - librosa
